######################################################################
# Automatically generated by qmake (2.01a) mar. sept. 17 09:15:56 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += multimedia.h
SOURCES += main.cpp multimedia.cpp
